# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-15 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='flag',
        ),
    ]
